import { Crown, Film, Gamepad2, Stars } from 'lucide-react';

export type WhoAmITheme = {
  id: string;
  name: string;
  description: string;
  color: string;
  textColor: string;
  icon: React.ElementType;
  personalities: string[];
};

//teste commit

export const WHOAMI_THEMES: WhoAmITheme[] = [
  {
    id: 'historico',
    name: 'Personagens Históricos',
    description: 'Deuses da história, inventores e líderes.',
    color: 'bg-amber-100',
    textColor: 'text-amber-900',
    icon: Crown,
    personalities: [
      'Abraham Lincoln',
      'Ada Lovelace',
      'Adam Smith',
      'Alan Turing',
      'Albert Einstein',
      'Aleijadinho',
      'Alexandre, o Grande',
      'Amelia Earhart',
      'Américo Vespúcio',
      'Anita Garibaldi',
      'Anne Frank',
      'Aristóteles',
      'Benjamin Franklin',
      'Buda (Siddhartha Gautama)',
      'Calígula',
      'Carlos drummond de andrade',
      'Charles Darwin',
      'Che Guevara',
      'Chiquinha Gonzaga',
      'Cleópatra',
      'Confúcio',
      'Cristóvão Colombo',
      'Dalai Lama',
      'Dante Alighieri',
      'Dom Pedro II',
      'Edgar Allan Poe',
      'Fernão de Magalhães',
      'Fidel Castro',
      'Fiódor Dostoiévski',
      'Florence Nightingale',
      'Frédéric Chopin',
      'Frida Kahlo',
      'Friedrich Nietzsche',
      'F.W. Murnau',
      'Gabriel García Márquez',
      'Galileu Galilei',
      'Garrincha',
      'Gengis Khan',
      'George Washington',
      'Getúlio Vargas',
      'Gilgamesh',
      'Giuseppe Garibaldi',
      'Heitor Villa-Lobos',
      'Homero',
      'Immanuel Kant',
      'Isaac Newton',
      'Jean-Jacques Rousseau',
      'Jesus de Nazaré',
      'Joana d\'Arc',
      'Joaquim Nabuco',
      'Johann Sebastian Bach',
      'Júlio César',
      'Juscelino Kubitschek',
      'Karl Marx',
      'Lampião',
      'Leonardo da Vinci',
      'Liev Tolstoi',
      'Lord Byron',
      'Ludwig van Beethoven',
      'Luísa Todi',
      'Machado de Assis',
      'Madre Teresa de Calcutá',
      'Mahatma Gandhi',
      'Malala Yousafzai',
      'Profeta Muhammad (S.A.A.S)',
      'Marco Polo',
      'Marcus Aurelius',
      'Marechal Deodoro da Fonseca',
      'Maria Bonita',
      'Marie Curie',
      'Martin Luther King Jr.',
      'Michelangelo',
      'Miguel de Cervantes',
      'Moisés',
      'Monalisa',
      'Nabucodonosor II',
      'Napoleão Bonaparte',
      'Nefertiti',
      'Neil Armstrong',
      'Nelson Mandela',
      'Nero',
      'Nikola Tesla',
      'Nikolai Gogol',
      'Pablo Picasso',
      'Papa Doc',
      'Papa Leão XIV',
      'Papa Francisco',
      'Papa João Paulo II',
      'Pedro Álvares Cabral',
      'Platão',
      'Princesa Isabel',
      'Rainha Elizabeth I',
      'Rainha Vitória',
      'Ramsés II',
      'René Descartes',
      'Rosa Parks',
      'Rui Barbosa',
      'Sabrina Carpenter',
      'Salgado Filho',
      'Salvador Dalí',
      'Santos Dumont',
      'Sigmund Freud',
      'Simon Bolívar',
      'Sócrates',
      'Spartacus',
      'Stephen Hawking',
      'Sun Tzu',
      'Thomas Edison',
      'Thomas Jefferson',
      'Tiradentes',
      'Tutancâmon',
      'Vasco da Gama',
      'Vincent van Gogh',
      'Vital Brazil',
      'Voltaire',
      'William Shakespeare',
      'William Wallace',
      'Winston Churchill',
      'Wolfgang Amadeus Mozart',
      'Xanana',
      'Yuri Gagarin',
      'Zumbi dos Palmares'
    ]
  },
  {
    id: 'cultura-pop',
    name: 'Cultura Pop & Famosos',
    description: 'Atores, cantores, influencers e celebridades.',
    color: 'bg-pink-100',
    textColor: 'text-pink-900',
    icon: Stars,
    personalities: [
      'Adele',
      'Alcione',
      'Alfred Hitchcock',
      'Alok',
      'Ana Maria Braga',
      'Angélica',
      'Angelina Jolie',
      'Anitta',
      'Ariana Grande',
      'ASAP Rocky',
      'Ayrton Senna',
      'Bebeto',
      'Bela Lugosi',
      'Beyoncé',
      'Bob Marley',
      'Brad Pitt',
      'Britney Spears',
      'Bruna Marquezine',
      'Bruno Mars',
      'Bud Abbott',
      'Caetano Veloso',
      'Carlinhos Maia',
      'Casimiro (Cazé)',
      'Cazuza',
      'Chico Buarque',
      'Cristiano Ronaldo',
      'Dario Argento',
      'David Bowie',
      'Dedé Santana',
      'Diego Maradona',
      'Djavan',
      'Drake',
      'Ed Sheeran',
      'Ed Motta',
      'Eddie Murphy',
      'Ed Warren',
      'Eliana',
      'Elis Regina',
      'Elton John',
      'Elvis Presley',
      'Eminem',
      'Fátima Bernardes',
      'Faustão',
      'Felipe Neto',
      'Fernanda Montenegro',
      'Freddie Mercury',
      'Galvão Bueno',
      'George Waggner',
      'Gilberto Gil',
      'Gisele Bündchen',
      'Grazi Massafera',
      'Gugu',
      'Gustavo Kuerten',
      'Gusttavo Lima',
      'Ivete Sangalo',
      'Jair Messias Bolsonaro',
      'Jennifer Lawrence',
      'Jô Soares',
      'John Carpenter',
      'John Lennon',
      'Johnny Depp',
      'Jorge Ben Jor',
      'JS da Torre',
      'Juliette Freire',
      'Justin Bieber',
      'Katy Perry',
      'Keanu Reeves',
      'Kim Kardashian',
      'Kylie Jenner',
      'Lady Gaga',
      'Lázaro Ramos',
      'LeBron James',
      'Leonardo DiCaprio',
      'Lewis Hamilton',
      'Lionel Messi',
      'Lionel Richie',
      'Lon Chaney',
      'Lon Chaney Jr.',
      'Lorraine Warren',
      'Lou Costello',
      'Luan Santana',
      'Luciano Huck',
      'Ludmilla',
      'Luísa Sonza',
      'Madonna',
      'Major RD',
      'Marília Mendonça',
      'Marilyn Monroe',
      'Marina Ruy Barbosa',
      'Marlon Brando',
      'Marta',
      'Marta Vieira da Silva',
      'Marta Suplicy',
      'Martina Navratilova',
      'Martinalia',
      'Martinho da Vila',
      'Marquês de Pombal',
      'Marquês de Sade',
      'Mia Goth',
      'Michael Jackson',
      'Michael Jordan',
      'Mussum',
      'Nelson Gonçalves',
      'Nelson Rodrigues',
      'Neymar',
      'Pabllo Vittar',
      'Paul McCartney',
      'Pedrin',
      'Pelé',
      'Poze do Rodo',
      'Renato Aragão (Didi)',
      'Renato Russo',
      'Rihanna',
      'Rita Lee',
      'Robert Dow Ney Jr.',
      'Roberto Carlos',
      'Rodrigo Faro',
      'Ronaldinho Gaúcho',
      'Ronaldo Fenômeno',
      'Sabrina Carpenter',
      'Sabrina Sato',
      'Scarlett Johansson',
      'Selena Gomez',
      'Selton Mello',
      'Serena Williams',
      'Shakira',
      'Silvio Santos',
      'Snoop Dogg',
      'Supla',
      'Taís Araújo',
      'Taylor Swift',
      'Tim Maia',
      'Tom Cruise',
      'Travis Scott',
      'Tupac Shakur',
      'Usain Bolt',
      'Vicent Prince',
      'Virginia Fonseca',
      'Wagner Moura',
      'Whindersson Nunes',
      'Will Smith',
      'William Bonner',
      'Xuxa',
      'Zacarias',
      'Zeca Pagodinho',
      'Zendaya'
    ]
  },
  {
    id: 'geek',
    name: 'Geek & Super-Heróis',
    description: 'Universo dos quadrinhos, animes e games.',
    color: 'bg-indigo-100',
    textColor: 'text-indigo-900',
    icon: Gamepad2,
    personalities: [
      'All Might',
      'Anakin Skywalker',
      'Aquaman',
      'Arlequina',
      'Arqueiro Verde',
      'Arthur Morgan',
      'Ash Ketchum',
      'Bane',
      'Batman',
      'Bowser',
      'C-3PO',
      'Capitã Marvel',
      'Capitão América',
      'Charada',
      'Charizard',
      'Chewbacca',
      'Ciborgue',
      'Ciclope',
      'Coringa',
      'Darth Vader',
      'Deadpool',
      'Donkey Kong',
      'Doutor Estranho',
      'Doutor Octopus',
      'Dr. Eggman',
      'Duas-Caras',
      'Duende Verde',
      'Ellie Williams',
      'Eren Yeager',
      'Espantalho(DC)',
      'Estelar',
      'Feiticeira Escarlate',
      'Fera (Marvel)',
      'Flash',
      'Freeza',
      'Ganondorf',
      'Geralt de Rívia',
      'Gohan',
      'Goku',
      'Han Solo',
      'Hera Venenosa',
      'Homem de Ferro',
      'Homem-Aranha',
      'Homem-Formiga',
      'Hulk',
      'Ichigo Kurosaki',
      'Izuku Midoriya',
      'Jean Grey',
      'Jiraiya',
      'Joel Miller',
      'Kakashi Hatake',
      'KGBesta',
      'Knuckles',
      'Kratos',
      'Kylo Ren',
      'L',
      'Lanterna Verde',
      'Lara Croft',
      'Levi Ackerman',
      'Lex Luthor',
      'Light Yagami',
      'Link',
      'Loki',
      'Luigi',
      'Luke Skywalker',
      'Magneto',
      'Majin Boo',
      'Master Chief',
      'Mega Man',
      'Mercúrio',
      'Mestre Yoda',
      'Mikasa Ackerman',
      'Miles Morales',
      'Mulher-Maravilha',
      'Naruto',
      'Nathan Drake',
      'Nezuko Kamado',
      'Noturno',
      'Obi-Wan Kenobi',
      'Orochimaru',
      'Pac-Man',
      'Pantera Negra',
      'Pikachu',
      'Pinguim',
      'Princesa Leia',
      'Princesa Peach',
      'Princesa Zelda',
      'Professor X',
      'R2-D2/Arturito',
      'Ravena',
      'Rey Skywalker',
      'Robin',
      'Ryuk',
      'Sabrina Carpenter',
      'Sailor Moon',
      'Saitama',
      'Sakura Haruno',
      'Sans (Undertale)',
      'Sasuke Uchiha',
      'Shadow',
      'Sonic',
      'Spider-Gwen',
      'Steve (Minecraft)',
      'Super Mario',
      'Superman',
      'Tails',
      'Tanjiro Kamado',
      'Tempestade',
      'Thanos',
      'Thor',
      'Tsunade',
      'Ultron',
      'Vampira',
      'Vash, o estouro da boiada',
      'Vegeta',
      'Venom',
      'Vespa',
      'Visão',
      'Viúva Negra',
      'Waluigi',
      'Wario',
      'Wolverine',
      'Yoshi'
    ]
  },
  {
    id: 'ficcao',
    name: 'Filmes & Séries',
    description: 'Personagens icônicos do cinema e TV.',
    color: 'bg-slate-200',
    textColor: 'text-slate-900',
    icon: Film,
    personalities: [
      'Aladdin',
      'Alice (No País das Maravilhas)',
      'Alvo Dumbledore',
      'Andre Toulon',
      'Anna De Arendelle',
      'Aragorn',
      'Ariel (Pequena Sereia)',
      'Arya Stark',
      'Axel Travers',
      'Barbie',
      'Barney Stinson',
      'Bart Simpson',
      'Bela (A Bela e a Fera)',
      'Bella Swan',
      'Beowulf',
      'Billy Butcherson',
      'Bjor Seligsson',
      'Bob Esponja',
      'Branca de Neve',
      'Bruxa do 71',
      'Burro falante',
      'Buzz Lightyear',
      'Capitão Gancho',
      'Cersei Lannister',
      'Chandler Bing',
      'Chapeleiro Maluco',
      'Chapolin Colorado',
      'Chaves',
      'Chiquinha',
      'Cinderela',
      'Conde Orlok',
      'Coringa',
      'Daenerys Targaryen',
      'Darth Vader',
      'Daryl Dixon',
      'Dona Florinda',
      'Dorothy Gale',
      'Draco Malfoy',
      'Dustin Henderson',
      'Dwight Schrute',
      'Edward Cullen',
      'Eleven',
      'Elsa',
      'Espantalho (Oz)',
      'Fera (A Bela e a Fera)',
      'Fiona',
      'Forrest Gump',
      'Frodo Bolseiro',
      'Freddy Krueger',
      'Gandalf',
      'Gato de Botas',
      'Gênio (Aladdin)',
      'Gollum',
      'Gomez Addams',
      'Gregory House',
      'Hamlet',
      'Harry Potter',
      'Hércules',
      'Hermione Granger',
      'Homem de Lata',
      'Homer Simpson',
      'Iago',
      'Indiana Jones',
      'Jack Sparrow',
      'Jacob Black',
      'Jafar',
      'James Bond',
      'Jane Porter',
      'Jasmine',
      'Jason Vorhees',
      'Jesse Pinkman',
      'Jessie',
      'Jim Halpert',
      'Joey Tribbiani',
      'Jon Snow',
      'Katniss Everdeen',
      'Kiko',
      'Leão Covarde',
      'Legolas',
      'Leonard Hofstadter',
      'Lilly Evenhart',
      'Lily Aldrin',
      'Lisa Simpson',
      'Lord Farquaad',
      'Lord Voldemort',
      'Lucas Sinclair',
      'Lula Molusco',
      'Marcus Dryden',
      'Marshall Eriksen',
      'Maggie Simpson',
      'Marge Simpson',
      'Michael Scott',
      'Mike Wheeler',
      'Monica Geller',
      'Morpheus',
      'Morticia Addams',
      'Mufasa',
      'Mulan',
      'Ned Flanders',
      'Negan',
      'Neo (Matrix)',
      'Otelo',
      'Olaf',
      'Pam Beesly',
      'Patrick Estrela',
      'Peeta Mellark',
      'Penny (TBBT)',
      'Peter Pan',
      'Phoebe Buffay',
      'Pinhead',
      'Plankton',
      'Professor (La Casa de Papel)',
      'Professor Girafales',
      'Pumba',
      'Rachel Green',
      'Rainha de Copas',
      'Rick Grimes',
      'Robin Sparkles',
      'Robin Scherbatsky',
      'Robin Trubotsky',
      'Rony Weasley',
      'Ross Geller',
      'Sabrina Carpenter',
      'Sandy Bochechas',
      'Saul Goodman',
      'Sauron',
      'Saya Kurosaki',
      'Scar',
      'Senhor Barriga',
      'Seu Madruga',
      'Seu Sirigueijo',
      'Severo Snape',
      'Sheldon Cooper',
      'Sherlock Holmes',
      'Shrek',
      'Simba',
      'Sininho',
      'Sr. Cabeça de Batata',
      'Steve Harrington',
      'Tarzan',
      'Ted Mosby',
      'Timão',
      'Tony Montana',
      'Tony Soprano',
      'Trinity',
      'Tyler Durden',
      'Tyrion Lannister',
      'Vecna',
      'Victor Ashford',
      'Victor Crowley',
      'Vito Corleone',
      'Walter White',
      'Wednesday Addams',
      'Will Byers',
      'Willy Wonka',
      'Woody',
      'Zoe Rayne'
    ]
  },
];
